### ISSUE TITLE
refactor: create mason_cli

### ISSUE THREAD

**Issue by passsy** [felangel/mason#156]
I'm using mason to ship templates with my cli. The APIs I'm using in the cli are `MasonBundle.fromJson`, `MasonGenerator.fromBundle` and `MasonGenerator.generate`.

There are dependencies in the current `mason` package that might cause unnecessary conflicts. Unnecessary because they aren't required for mason to generate templates, but only for the cli part of the package:

```
dependencies:
  args: ^2.1.0
  http: ^0.13.3
  pub_updater: ^0.2.1
  universal_io: ^2.0.4
```

`mason` should be split into two packages: 
- One for the cli part (with `/bin` directory)
- One for the tempalte/generation part with minimal dependencies

This split allows the CLI to use and ship the latest dependencies while allowing wide dependency ranges for packages which use `mason` as dependency.

While it sounds like a duplicate of https://github.com/felangel/mason/issues/91, I think this split alone is easier to achieve and it fixes a realworld problem.

**Comment by felangel** [comment]
Hi @passsy 👋 
Thanks for opening an issue!

I agree it would make sense to decouple the CLI from the generator (similar to #91). My only comments are:
- `universal_io` would still be a dependency for the generator because of the I/O and logging (stdout, stderr)
- I'm still not sure if it'd be better to rename `mason` to `mason_cli` and keep `mason` as the generator or whether to keep `mason` as the cli and create `mason_core`/`mason_generator`/`mason_engine` to contain the generator.

Do you prefer having `mason` and `mason_cli`?

Thanks again!

**Comment by passsy** [comment]
I prefer `mason_cli` and `mason` as the generator. Although it is a breaking change, but that is ok for version `0.0.1-dev` 😉 

Alternatively `mason` and `mason_generator` would be fine too 🤷
