### ISSUE TITLE
feat: Support federated plugin template generateion

### ISSUE THREAD

**Issue by Sunbreak** [felangel/mason#95]
**Description**

Support federated plugin template generateion

**Requirements**

- [ ] platform_interface
- [ ] Android
- [ ] iOS
- [ ] Windows
- [ ] macOS
- [ ] Web

**Additional Context**

https://github.com/flutter/flutter/issues/43284, official support is missing. Could we have one template with `mason`?

**Comment by Ascenio** [comment]
Can't we make that as a brick? I guess it's better to avoid new features when what it's currently working can do the job.

**Comment by Sunbreak** [comment]
> Can't we make that as a brick? I guess it's better to avoid new features when what it's currently working can do the job.

Didn't know that. I'll try. Thanks a lot~

**Comment by felangel** [comment]
Hi @Sunbreak 👋 
Thanks for opening an issue!

As @Ascenio mentioned, there's nothing preventing you from creating a brick for a new flutter plugin. I also wanted to note that the [very_good_cli](https://github.com/VeryGoodOpenSource/very_good_cli) will soon provide support for creating a new plugin using this approach 👍 

Closing for now since there don't appear to be changes in mason required to support this.

**Comment by Sunbreak** [comment]
https://github.com/woodemi/quick_flutter.brick

**Comment by Sunbreak** [comment]
Finally I got there: https://github.com/woodemi/quick_flutter.brick/tree/0.3.0

/ | Android | iOS | Web | macOS | Windows | Linux
--- | --- | --- | --- | --- | --- | ---
APP | ✅ | ✅ | ✅ | ✅ | ✅ | ✅
plugin | ✅ | ✅ | ✅ | ✅ | ✅ | ✅
federated-plugin | ✅ | ✅ | ✅ | ✅ | ✅ | ✅
